### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by debortoli** [romulogcerqueira/sonar_simulation-buildconf#1]
Hi,

This is very interesting work! I am trying to install your simulator with now experience or knowledge of packages like Rock or Ruby. Can you please list the dependencies of this simulator?

I have installed your package (i.e. I have the example scripts following your instructions in the README). I am now running into problems running the imaging sonar scripts due to a lack of "vizkit", which I assume is a part of Rock? Thanks!

**Comment by romulogcerqueira** [comment]
Hi @debortoli,

thanks. It's good to hear that the sonar simulator is interesting to you. `vizkit` is the graphical package of Rock and it is expected to run without problems. Maybe `vizkit` package was updated and we need to do something in our side.

Could you present the error output?

**Comment by debortoli** [comment]
Thanks for the response! The error I was getting was: **`require': cannot load such file -- vizkit** when I ran sonar_multibeam-run.rb . This was before I had installed Rock separately from your package. 

So I have tried to install Rock myself and then your package and that has not worked (the Rock bootstrap.sh script is not working properly for some reason, so I have been unable to fully install Rock). 

Anyways, the error I was getting to me suggested I had some prior dependency issues, so it may be helpful to get any system parameters you expect (e.g. Ruby version) when installing your package. 

Thanks

**Comment by debortoli** [comment]
Sorry for the lack of detail in my last post. So I have tried to not install Rock before installing your package. I ran sudo apt-get install ruby and got version 1.9.3p555 (I'm on Ubuntu 14.04). Then I wget and ran bootstrap.sh. I got the following error:

*********************************************************************************************
2017-11-08 16:08:55 URL:https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_install [25221/25221] -> "autoproj_install" [1]
autoproj_install:265: syntax error, unexpected tLABEL
            def install_bundler(gem_program, silent: false)
                                                    ^
autoproj_install:277: syntax error, unexpected tPOW, expecting ')'
...m_home, 'bin')}", 'bundler', **redirection)
...                               ^
autoproj_install:322: dynamic constant assignment
            EXCLUDED_FROM_SHIMS = %w{rake thor}
                                 ^
autoproj_install:447: dynamic constant assignment
...        ENV_BUNDLE_GEMFILE_RX = /^(\s*ENV\[['"]BUNDLE_GEMFIL...
...                               ^
autoproj_install:600: syntax error, unexpected keyword_end, expecting $end
*********************************************************************************************


So then I tried to update Ruby using rbenv. I updated to version 2.4.2 (I think Rock only works with 2.0+).  I selected "no" when it asked if C++ should be enabled for Rock packages. I then ran bootstrap.sh and got the following error:


*********************************************************************************************
sonar_simulation is selected in the manifest or on the command line, but it requires gui/vizkit3d_world, simulation/orogen/imaging_sonar_simulation, gui/orogen/vizkit3d_world, and all these packages are excluded from the build:
  gui/vizkit3d_world: libclang-castxml is marked as unavailable for this operating system (dependency chain: gui/vizkit3d_world>gui/robot_model>gui/vizkit>drivers/orogen/transformer>tools/orogen_metadata>typelib>castxml>libclang-castxml)
  simulation/orogen/imaging_sonar_simulation: libclang-castxml is marked as unavailable for this operating system (dependency chain: simulation/orogen/imaging_sonar_simulation>gui/orogen/vizkit3d_world>tools/orogen_metadata>typelib>castxml>libclang-castxml)
  gui/orogen/vizkit3d_world: libclang-castxml is marked as unavailable for this operating system (dependency chain: gui/orogen/vizkit3d_world>tools/orogen_metadata>typelib>castxml>libclang-castxml)
*********************************************************************************************

Do you know what could be causing this? Thank you!

**Comment by romulogcerqueira** [comment]
Hey!

we have used and tested using Ubuntu 16.04 with Ruby 2.3.1. Could you reinstall the imaging sonar simulation using this Ruby version?

**Comment by debortoli** [comment]
Ok, I tried it with Ruby 2.3.1 and Ubuntu 14.04 and it was unable to build (for a variety of reasons I could not figure out). I then tried it with Ubuntu 16.04 and it worked! Thanks!
