### ISSUE TITLE
cannot load such file -- rock/bundles

### ISSUE THREAD

**Issue by chyphen777** [romulogcerqueira/sonar_simulation-buildconf#10]

**Comment by chyphen777** [comment]
I am trying to run sonar_multibeam-run.rb, but got errors:
cchien@G751JY:~/sonar_simulation/simulation/examples$ ruby sonar_multibeam-run.rb
/usr/share/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rock/bundles (LoadError)
	from /usr/share/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sonar_multibeam-run.rb:1:in `<main>'
Any suggestions how to fix this issue?   

Thanks, CC

**Comment by chyphen777** [comment]
Fixed the issue by reinstall autoproj.

**Comment by ehratjon** [comment]
In case this happens again: 
You might have forgotten to load the provided environment. Do so by typing 
`source env.sh`
in the base directory of the project.
