### ISSUE TITLE
communication failed with #<TaskContext: Orocos::TaskContext//sonar_multibeam> (Orocos::CORBA::ComError)

### ISSUE THREAD

**Issue by chyphen777** [romulogcerqueira/sonar_simulation-buildconf#11]
When running ruby sonar_multibeam_rb I got several errors including communication failed, preceded by a warning (QApplication was not created in the main() thread).  Not sure if they are related.  Any suggestions how to fix those errors:  Thanks. CC

cc@G751JY:~/sonar_simulation/simulation/examples$ ruby sonar_multibeam-run.rb 
WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment variable is deprecated
WARN: just put a file called typelib_plugin.rb into a subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
WARN: offending dir: /home/cchien/sonar_simulation/install/share/typelib/ruby
Bundles[INFO]: No bundle currently selected
Typelib[WARN]: possible old-style access on Types, use Types.namespace.of.Type instead of Types::Namespace::Of::Type
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:111:in `find_type'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:161:in `resolve_call_from_exported_registry'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:199:in `const_missing'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:47:in `reset'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:43:in `initialize'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `new'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `transformer'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:29:in `use_bundle_loader'
Typelib[WARN]:   /home/cchien/sonar_simulation/base/scripts/lib/rock/bundles.rb:361:in `load'
Typelib[WARN]:   /home/cchien/sonar_simulation/simulation/examples/lib/rock_gazebo.rb:74:in `initialize'
Typelib[WARN]:   sonar_multibeam-run.rb:9:in `<main>'
Typelib[WARN]: possible old-style access on Types, use Types.namespace.of.Type instead of Types::Namespace::Of::Type
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:88:in `find_namespace'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:183:in `resolve_call_from_exported_registry'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:199:in `const_missing'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:47:in `reset'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:43:in `initialize'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `new'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `transformer'
Typelib[WARN]:   /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:29:in `use_bundle_loader'
Typelib[WARN]:   /home/cchien/sonar_simulation/base/scripts/lib/rock/bundles.rb:361:in `load'
Typelib[WARN]:   /home/cchien/sonar_simulation/simulation/examples/lib/rock_gazebo.rb:74:in `initialize'
Typelib[WARN]:   sonar_multibeam-run.rb:9:in `<main>'
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
WARNING: QApplication was not created in the main() thread.
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `do_configure': communication failed with #<TaskContext: Orocos::TaskContext//sonar_multibeam>
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `block in configure'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:92:in `configure'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/simulation/examples/lib/common.rb:10:in `setup_task'
orocos.rb[WARN]:     sonar_multibeam-run.rb:25:in `block in <main>'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
orocos.rb[WARN]:     sonar_multibeam-run.rb:14:in `<main>'
orocos.rb[WARN]: clean shutdown of process sonar_multibeam failed
orocos.rb[WARN]: sending 2 to sonar_multibeam
/home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `do_configure': communication failed with #<TaskContext: Orocos::TaskContext//sonar_multibeam> (Orocos::CORBA::ComError)
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `block in configure'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:92:in `configure'
	from /home/cchien/sonar_simulation/simulation/examples/lib/common.rb:10:in `setup_task'
	from sonar_multibeam-run.rb:25:in `block in <main>'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	from sonar_multibeam-run.rb:14:in `<main>'

**Comment by chyphen777** [comment]
When I switched the order of setup_task() and setup_widgets(), in sonar_multibeam.rb, the warning of "QApplication() not created" was gone, so was communication error.  However I got stuck at different errors.  Any suggestion how to track down and/or fix those errors.  Thanks, CC
Truncated log:
0.073 [ Warning][TaskContextServer()] CTaskContext 'sonar_multibeam' already bound to CORBA Naming Service.
0.073 [ Warning][TaskContextServer()] Trying to rebind... done. New CTaskContext bound to Naming Service.
0.074 [ Warning][TaskContextServer()] CTaskContext 'sonar_multibeam_Logger' already bound to CORBA Naming Service.
0.074 [ Warning][TaskContextServer()] Trying to rebind... done. New CTaskContext bound to Naming Service.
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   sonar_multibeam-run.rb:24:in `block in <main>': undefined local variable or method `task' for main:Object
Did you mean?  task
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
orocos.rb[WARN]:     /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
orocos.rb[WARN]:     sonar_multibeam-run.rb:14:in `<main>'
sonar_multibeam-run.rb:24:in `block in <main>': undefined local variable or method `task' for main:Object (NameError)
Did you mean?  task
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	from sonar_multibeam-run.rb:14:in `<main>'

**Comment by chyphen777** [comment]
Silly me.  Task was not defined for setup-widegets after switching of code blocks.  Now got other bugs to track.  Close this issue.

**Comment by 1ADZX** [comment]
> When running ruby sonar_multibeam_rb I got several errors including communication failed, preceded by a warning (QApplication was not created in the main() thread). Not sure if they are related. Any suggestions how to fix those errors: Thanks. CC
> 
> cc@G751JY:~/sonar_simulation/simulation/examples$ ruby sonar_multibeam-run.rb
> WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment variable is deprecated
> WARN: just put a file called typelib_plugin.rb into a subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
> WARN: offending dir: /home/cchien/sonar_simulation/install/share/typelib/ruby
> Bundles[INFO]: No bundle currently selected
> Typelib[WARN]: possible old-style access on Types, use Types.namespace.of.Type instead of Types::Namespace::Of::Type
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:111:in `find_type' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:161:in `resolve_call_from_exported_registry'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:199:in `const_missing' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:47:in `reset'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:43:in `initialize' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `new'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `transformer' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:29:in `use_bundle_loader'
> Typelib[WARN]: /home/cchien/sonar_simulation/base/scripts/lib/rock/bundles.rb:361:in `load' Typelib[WARN]: /home/cchien/sonar_simulation/simulation/examples/lib/rock_gazebo.rb:74:in `initialize'
> Typelib[WARN]: sonar_multibeam-run.rb:9:in `<main>' Typelib[WARN]: possible old-style access on Types, use Types.namespace.of.Type instead of Types::Namespace::Of::Type Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:88:in `find_namespace'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:183:in `resolve_call_from_exported_registry' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/typelib/registry_export.rb:199:in `const_missing'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:47:in `reset' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:43:in `initialize'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `new' Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:282:in `transformer'
> Typelib[WARN]: /home/cchien/sonar_simulation/install/lib/ruby/2.3.0/transformer/runtime.rb:29:in `use_bundle_loader' Typelib[WARN]: /home/cchien/sonar_simulation/base/scripts/lib/rock/bundles.rb:361:in `load'
> Typelib[WARN]: /home/cchien/sonar_simulation/simulation/examples/lib/rock_gazebo.rb:74:in `initialize' Typelib[WARN]: sonar_multibeam-run.rb:9:in `
> 
> '
> OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
> OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
> OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
> WARNING: QApplication was not created in the main() thread.
> orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
> orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `do_configure': communication failed with #<TaskContext: Orocos::TaskContext//sonar_multibeam> orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `block in configure'
> orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions' orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:92:in `configure'
> orocos.rb[WARN]: /home/cchien/sonar_simulation/simulation/examples/lib/common.rb:10:in `setup_task' orocos.rb[WARN]: sonar_multibeam-run.rb:25:in `block in '
> orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run' orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
> orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run' orocos.rb[WARN]: /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
> orocos.rb[WARN]: sonar_multibeam-run.rb:14:in `<main>' orocos.rb[WARN]: clean shutdown of process sonar_multibeam failed orocos.rb[WARN]: sending 2 to sonar_multibeam /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `do_configure': communication failed with #<TaskContext: Orocos::TaskContext//sonar_multibeam> (Orocos::CORBA::ComError)
> from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `block in configure' from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
> from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:92:in `configure' from /home/cchien/sonar_simulation/simulation/examples/lib/common.rb:10:in `setup_task'
> from sonar_multibeam-run.rb:25:in `block in <main>' from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
> from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard' from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
> from /home/cchien/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run' from sonar_multibeam-run.rb:14:in `'

Can you elaborate on how you solve this problem? Because I have similar problems, thank you very much

**Comment by ricardoGrando** [comment]
> Silly me. Task was not defined for setup-widegets after switching of code blocks. Now got other bugs to track. Close this issue.

I got this error too. Could you explain better how you solved it?
