### ISSUE TITLE
BUG when running ruby unit_test_multibeam.rb

### ISSUE THREAD

**Issue by nsalman** [romulogcerqueira/sonar_simulation-buildconf#2]
Hi Romulo,

I am having a bug when running either **ruby unit_test_multibeam.rb** as can be seen below 

**~/Documents/Sonar_sim_2.3.1/simulation/orogen/imaging_sonar_simulation/test$** **ruby unit_test_multibeam.rb** 

```
Run options: --seed 36201

# Running:

OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
orogen_default_imaging_sonar_simulation__MultibeamSonarTask: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
Eorogen_default_imaging_sonar_simulation__MultibeamSonarTask: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
```
or when running **~/Documents/Sonar_sim_2.3.1/simulation/orogen/imaging_sonar_simulation/build$ ./orogen_default_imaging_sonar_simulation__MultibeamSonarTask** 

which gives the following error:

```
orogen_default_imaging_sonar_simulation__MultibeamSonarTask: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

```
I would appreciate your help. Please note that all other packages - i.e. normal_depth_map, gpu_sonar_simulation - simply work. imaging_sonar_simulation on the other hands doesn't.

Thanks.

**Comment by romulogcerqueira** [comment]
Please try:

`$ gem install bundler`

and perform again

`$ aup -k; amake -k`

**Comment by nsalman** [comment]
I had tried that also.

**~/Documents/Sonar_sim_2.3.1$** gem install bundler
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 4 seconds
1 gem installed
**~/Documents/Sonar_sim_2.3.1$** gem list

*** LOCAL GEMS ***

autobuild (1.12.1)
autoproj (2.3.1)
autorespawn (0.6.0)
backports (3.11.0)
bigdecimal (1.2.8)
binding_of_caller (0.8.0, 0.7.3)
builder (3.2.3)
bundle (0.0.1)
bundler (1.16.1)
bundler-unload (1.0.2)
concurrent-ruby (1.0.5)

**~/Documents/Sonar_sim_2.3.1$** aup -k; amake -k
  operating system: ubuntu,debian - 16.04,16.04.3,lts,xenial,xerus
  updating bundler                                                
GemWrappers: Can not wrap missing file: bundle
GemWrappers: Can not wrap missing file: bundler   <===== Is that normal ?

Also, here is the ruby version I am using  (using RVM)
 
**~/Documents/Sonar_sim_2.3.1$** rvm list
   ruby-1.9.1-p431 [ x86_64 ]
   ruby-2.0.0-p648 [ x86_64 ]
=* ruby-2.3.1 [ x86_64 ]   (**CURRENT**)
   ruby-2.4.1 [ x86_64 ]


 
note that I am also using OSG version 3.4 ==> meaning I had to change the code of WindowCaptureCallback.hpp and WindowCaptureCallback.cpp to make it work.

**Comment by nsalman** [comment]
Some complementary information - _I have completely uninstalled RVM, Reinstalled it with default Ruby 2.3.1 restarted machine then went through the steps on your github once more - created a older Sonar_simulation_clean_2.3.1_ 

_Note: The first commands in your bootstrap script work well_
 

```
#!/bin/sh

set -e

test -f "autoproj_install" || wget -nv https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_install

export AUTOPROJ_OSDEPS_MODE=all
export AUTOPROJ_BOOTSTRAP_IGNORE_NONEMPTY_DIR=1

ruby autoproj_install
. ./env.sh
autoproj bootstrap git git@github.com:romulogcerqueira/sonar_simulation-buildconf.git

 

```
here is what happened when tried to run aup -k, then tried to check whether gem list contained bundler/bundle which it did:



**~$** cd Documents/Sonar_simulation_clean_2.3.1/
**~/Documents/Sonar_simulation_clean_2.3.1$** aup -k
  operating system: ubuntu,debian - 16.04,16.04.3,lts,xenial,xerus
  updating bundler                                                
GemWrappers: Can not wrap missing file: bundle
GemWrappers: Can not wrap missing file: bundler
  updating autoproj
  bundler: connected to https://rubygems.org/
  already up-to-date autoproj main configuration
  checking out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_cou  checking out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_cou  checked out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_coun  checked out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_coun  checked out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_count=10
  checked out git:git@github.com:/rock-core/package_set.git interactive=false push_to=git@github.com:/rock-core/package_set.git repository_id=github:/rock-core/package_set.git retry_coun                                                                                                                                                                                            whether C++11 should be enabled for Rock packages [no] ^X^C
Interrupted by user
**~/Documents/Sonar_simulation_clean_2.3.1$** ^C

**~/Documents/Sonar_simulation_clean_2.3.1$** gem list

*** LOCAL GEMS ***

autobuild (1.12.1)
autoproj (2.3.1)
autorespawn (0.6.0)
backports (3.11.0)
bigdecimal (1.2.8)
binding_of_caller (0.8.0, 0.7.3)
builder (3.2.3)
bundle (0.0.1)
bundler (1.16.1)
bundler-unload (1.0.2)
concurrent-ruby (1.0.5)
concurrent-ruby-ext (1.0.5)
cucumber (3.1.0)
cucumber-core (3.1.0)

I must be missing something? or is it supposed to do that ? I have on my machine OSG installed and Gazebo installed, Ruby 2.3.1, Gem 2.5.1 on Ubuntu 16.04 - from my experience once it does that at this stage I get the issues mentioned hereafter after aup-k and amake -k are completed:

*    simulation/normal_depth_map (works just fine)
*    simulation/gpu_sonar_simulation (works just fine)

but simulation/orogen/imaging_sonar_simulation/scripts (bot ruby scripts lead to many errors and segmentation faults which I am not sure how to resolve)
 
**>**ruby sonar_multibeam-run.rb
First the error that shows is : Bundles[INFO]: No bundle currently selected
At the end of the error message appears: ‘wait running’ : sonar_multibeam was started but crashed (Orocos::NotFound)

**Comment by nsalman** [comment]
some complementary information related to running:

**~/Documents/Sonar_simulation_clean_2.3.1/simulation/orogen/imaging_sonar_simulation/scripts**$ ruby sonar_scanning-run.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vizkit (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sonar_scanning-run.rb:1:in `<main>

**Comment by shubhamwagh** [comment]
On running FLS scanning simulation, I get error related to vizkit. re there anyother dependencies which I need to install?
ruby sonar_multibeam-run.rb
**Error Message** :
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vizkit (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from sonar_multibeam-run.rb:1:in <main>

@nsalman  were you able to fix this issue?
