### ISSUE TITLE
Running example fails. any solutions?

### ISSUE THREAD

**Issue by woensug-choi** [romulogcerqueira/sonar_simulation-buildconf#21]
Running example case fails. GUI shows up but quits right after with few seconds of delay.
Log attached.

`WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment variable is deprecated
WARN: just put a file called typelib_plugin.rb into a subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
WARN: offending dir: /home/eric/sonar_simulation/install/share/typelib/ruby
Bundles[INFO]: No bundle currently selected
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in imaging_sonar_simulation: use task_context "Name", subclasses: "Parent" do .. end instead
WARNING: QApplication was not created in the main() thread.
0.028 [ Warning][TaskContextServer()] CTaskContext 'sonar_multibeam' already bound to CORBA Naming Service.
0.029 [ Warning][TaskContextServer()] Trying to rebind... done. New CTaskContext bound to Naming Service.
0.034 [ Warning][TaskContextServer()] CTaskContext 'sonar_multibeam_Logger' already bound to CORBA Naming Service.
0.034 [ Warning][TaskContextServer()] Trying to rebind... done. New CTaskContext bound to Naming Service.
Vizkit[WARN]: deprecation: use Async API to connect the port /sonar_multibeam.sonar_samples to a widget or code block
orocos.rb[WARN]: TaskContextProxy /sonar_multibeam is already initialized with different options.
listening to gazebo:ssiv_bahia:ssiv_mockup_bahia for ssiv_mockup_bahia
listening to gazebo:ssiv_bahia:seafloor for seafloor
PNG lib warning : iCCP: known incorrect sRGB profile
PNG lib warning : iCCP: known incorrect sRGB profile
PNG lib warning : iCCP: known incorrect sRGB profile
PNG lib warning : iCCP: known incorrect sRGB profile
FRAGMENT glCompileShader "" FAILED
FRAGMENT Shader "" infolog:
0:166(7): error: illegal use of reserved word `output'
0:166(7): error: syntax error, unexpected ERROR_TOK, expecting ',' or ';'

glLinkProgram "" FAILED
Program "" infolog:
error: linking with uncompiled/unspecialized shader
Warning: detected OpenGL error 'invalid operation' at After Renderer::compile
RenderStage::runCameraSetUp(), FBO setup failed, FBO status= 0x8cdd
Warning: RenderStage::runCameraSetUp(State&) Pbuffer does not support multiple color outputs.
i965: Failed to submit batchbuffer: Invalid argument
PNG lib warning : iCCP: known incorrect sRGB profile
QSocketNotifier: Invalid socket 28 and type 'Read', disabling...
PNG lib warning : iCCP: known incorrect sRGB profile
FRAGMENT glCompileShader "object_shader_fragment_shader" FAILED
FRAGMENT Shader "object_shader_fragment_shader" infolog:
0:117(104): error: could not implicitly convert operands to relational operator
0:117(104): error: RHS of `&&' must be scalar boolean
0:121(6): error: could not implicitly convert operands to relational operator
0:121(6): error: if-statement condition must be scalar boolean
0:128(2): error: value of type int cannot be assigned to variable of type float

glLinkProgram "object_shader" FAILED
Program "object_shader" infolog:
error: linking with uncompiled/unspecialized shader
Warning: detected OpenGL error 'invalid operation' at After Renderer::compile
omniORB: (3) 2020-07-02 12:57:29.918755: Error: a servant has been deleted that is still activated.
      id: root<8> (active)
1.943 [ ERROR  ][RemoteInputPort::buildRemoteChannelOutput] Caught CORBA exception while creating a remote channel output:
1.943 [ ERROR  ][RemoteInputPort::buildRemoteChannelOutput] MARSHAL
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/output_port.rb:78:in `rescue in connect_to': failed to connect orocosrb_8752./sonar_multibeam.sonar_pose_cmd.5 => /sonar_multibeam.sonar_pose_cmd with policy {:type=>:data, :init=>false, :pull=>false, :data_size=>0, :size=>0, :lock=>:lock_free, :transport=>0, :name_id=>""}
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/output_port.rb:40:in `connect_to'
orocos.rb[WARN]:     /home/eric/sonar_simulation/gui/vizkit/lib/vizkit/qt_orocos.rb:35:in `connect_to'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/ports_base.rb:175:in `writer'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/ports_base.rb:187:in `write'
orocos.rb[WARN]:     /home/eric/sonar_simulation/simulation/examples/lib/common.rb:15:in `block in setup_task'
orocos.rb[WARN]:     /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
orocos.rb[WARN]:     /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `qt_metacall'
orocos.rb[WARN]:     /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `method_missing'
orocos.rb[WARN]:     /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `exec'
orocos.rb[WARN]:     /home/eric/sonar_simulation/gui/vizkit/lib/vizkit/vizkit.rb:146:in `exec'
orocos.rb[WARN]:     /home/eric/sonar_simulation/simulation/examples/lib/common.rb:77:in `setup_widgets'
orocos.rb[WARN]:     sonar_multibeam-run.rb:32:in `block in <main>'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
orocos.rb[WARN]:     /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
orocos.rb[WARN]:     sonar_multibeam-run.rb:17:in `<main>'
orocos.rb[WARN]: clean shutdown of /sonar_multibeam failed: Communication failed with corba #<TaskContext: Orocos::TaskContext//sonar_multibeam>
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `do_stop'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:94:in `block in stop'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/corba.rb:116:in `refine_exceptions'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/task_context.rb:92:in `stop'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1245:in `try_task_cleanup'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1277:in `block in kill'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:217:in `block in each_task'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:216:in `each'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:216:in `each_task'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1276:in `kill'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1378:in `block in guard'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1375:in `each'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1375:in `ensure in guard'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1381:in `guard'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
orocos.rb[WARN]: /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
orocos.rb[WARN]: sonar_multibeam-run.rb:17:in `<main>'
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
log writing failed. can't be called from trap context
orocos.rb[WARN]: clean shutdown of process sonar_multibeam failed
orocos.rb[WARN]: sending 2 to sonar_multibeam
Traceback (most recent call last):
	17: from sonar_multibeam-run.rb:17:in `<main>'
	16: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:136:in `run'
	15: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:847:in `run'
	14: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:1344:in `guard'
	13: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/process.rb:848:in `block in run'
	12: from sonar_multibeam-run.rb:32:in `block in <main>'
	11: from /home/eric/sonar_simulation/simulation/examples/lib/common.rb:77:in `setup_widgets'
	10: from /home/eric/sonar_simulation/gui/vizkit/lib/vizkit/vizkit.rb:146:in `exec'
	 9: from /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `exec'
	 8: from /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `method_missing'
	 7: from /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	 6: from /home/eric/.local/share/autoproj/gems/ruby/2.5.0/gems/qtbindings-4.8.6.5/lib/Qt/qtruby4.rb:2470:in `invoke'
	 5: from /home/eric/sonar_simulation/simulation/examples/lib/common.rb:15:in `block in setup_task'
	 4: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/ports_base.rb:187:in `write'
	 3: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/ports_base.rb:175:in `writer'
	 2: from /home/eric/sonar_simulation/gui/vizkit/lib/vizkit/qt_orocos.rb:35:in `connect_to'
	 1: from /home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/output_port.rb:40:in `connect_to'
/home/eric/sonar_simulation/tools/orocos.rb/lib/orocos/output_port.rb:78:in `rescue in connect_to': failed to connect orocosrb_8752./sonar_multibeam.sonar_pose_cmd.5 => /sonar_multibeam.sonar_pose_cmd with policy {:type=>:data, :init=>false, :pull=>false, :data_size=>0, :size=>0, :lock=>:lock_free, :transport=>0, :name_id=>""} (Orocos::ConnectionFailed)
`

**Comment by ehratjon** [comment]
The issue has some similarities to an issue [#15](https://github.com/romulogcerqueira/sonar_simulation/issues/15) i had.
Have you made sure you have a running GPU device? 
And have you tried to install [cuda](https://developer.nvidia.com/cuda-downloads) ?

**Comment by woensug-choi** [comment]
> some

You got it just right. Bought a new machine with a discrete GPU. Thank you.
