### ISSUE TITLE
Creating new Scene and animating a path

### ISSUE THREAD

**Issue by ehratjon** [romulogcerqueira/sonar_simulation-buildconf#22]
Hi Rômulo, 

I recently tried to add a custom scene to the simulator, first I tried to add a new scene under simulation/examples/lib/scenes.rb and adding all the files under the simulation/uwmodels/scenes directory following the examples. This somehow did not work. 
To find the error I wanted to work my way back in the easiest possible steps: I replaced the visual .osgb model in an existing scene after I verified that the scene is correct by visualizing it with "osgviewer visual.osgb". But in the simulation it is not being displyed.
Would you mind elaborating what your process of adding a new scene is?

Additionally is there a method on how to add a path for the sonar-camera to follow that I am missing, or would I have to program way-points into the ruby script?

In case you need more information let me know.
Thanks :)

**Comment by romulogcerqueira** [comment]
The scene elements are described in `.world` (https://github.com/romulogcerqueira/simulation-uwmodels/blob/master/scenes/ssiv_bahia/ssiv_bahia.world) and the element description is done in SDF files (https://github.com/romulogcerqueira/simulation-uwmodels/tree/master/sdf).

It is missing in README file how to create new scenes from scratch. Thanks for your contribution.

Also, you can modify the ruby files to insert the waypoints you want to run.
