### ISSUE TITLE
sonar.setRegularBeamBearings not found

### ISSUE THREAD

**Issue by roaddy** [romulogcerqueira/sonar_simulation-buildconf#24]
Hi，Nice work！May I ask where to find the function  sonar.setRegularBeamBearings in the source code? I can't find it in any of repos, especially simulation-gpu_sonar_simulation.

Thank you.

**Comment by romulogcerqueira** [comment]
Hi @roaddy, `sonar.setRegularBeamBearing()` is part of Rock's sonar datatype 

(`base::samples::Sonar` -> https://github.com/rock-core/base-types/blob/master/src/samples/Sonar.hpp#L199)

**Comment by roaddy** [comment]
> 
> 
> Hi @roaddy, `sonar.setRegularBeamBearing()` is part of Rock's sonar datatype
> 
> (`base::samples::Sonar` -> https://github.com/rock-core/base-types/blob/master/src/samples/Sonar.hpp#L199)

Thanks A Lot!
