### ISSUE TITLE
question about the multipath propagation

### ISSUE THREAD

**Issue by AronNoren** [romulogcerqueira/sonar_simulation-buildconf#28]
Hello Rômulo, sorry to bother you with another question. 

When creating a bowl-shaped object such as the cube with a hole, I was expecting to get multiple echoes back from the object as sound bounces back and forth within the bowl and then back to the receiver. I am however only seeing the primary reflections. Do you have any idea what this could be caused by?
![hollowcube](https://user-images.githubusercontent.com/47273486/111121794-6bb6be80-856d-11eb-958e-11869b5c316f.png)
![sonar](https://user-images.githubusercontent.com/47273486/111122779-cb619980-856e-11eb-9f91-a060f30184b7.png)

**Comment by romulogcerqueira** [comment]
Hi @AronNoren, this is a known issue: https://github.com/romulogcerqueira/simulation-normal_depth_map/issues/20

Feel free to contribute!

**Comment by AronNoren** [comment]
Thanks for the answer Rômulo, 
I see the issue now, complexity would grow very fast if all rays were kept and It's not trivial to determine which rays to keep if we allow for some self-reflection?
