### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by fansystem** [romulogcerqueira/sonar_simulation-buildconf#3]
:~/sonar_simulation$ sudo sh bootstrap.shDetected 'gem' to be /usr/bin/gem2.3
Detected bundler at /home/power/.autoproj/gems/ruby/2.3.0/bin/bundler
Installing autoproj in /home/power/.autoproj/gems/ruby/2.3.0
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.3.1
Using equatable 0.5.0
Using tty-color 0.4.2
Using pastel 0.7.2
Using necromancer 0.4.0
Using hitimes 1.2.6
Using timers 4.1.2
Using tty-cursor 0.5.0
Using tty-screen 0.6.4
Using wisper 2.0.0
Using tty-reader 0.2.0
Using tty-prompt 0.15.0
Using facets 3.1.0
Using utilrb 3.0.1
Using autobuild 1.13.0
Using backports 3.11.1
Using bundler 1.16.1
Using concurrent-ruby 1.0.5
Using ffi 1.9.23
Using rb-inotify 0.9.10
Using thor 0.20.0
Using tty-spinner 0.8.0
Using autoproj 2.6.0
Bundle complete! 2 Gemfile dependencies, 23 gems now installed.
Bundled gems are installed into `/home/power/.autoproj/gems`
starting the newly installed autoproj for stage2 install
saving temporary env.sh and .autoproj/env.sh
running 'autoproj envsh' to generate a proper env.sh
  updated: /home/power/sonar_simulation/env.sh
running 'autoproj osdeps' to re-install missing gems
Command finished successfully at 2018-04-05 22:25:24 +0900
  checkout of autoproj main configuration failed, deleting the source directory /home/power/sonar_simulation/autoproj
  ERROR: switching configuration failed: autoproj main configuration(/home/power/sonar_simulation/autoproj): failed in import phase
    'git clone -o autobuild git@github.com:romulogcerqueira/sonar_simulation-buildconf.git /home/power/sonar_simulation/autoproj' returned status 128
    see /home/power/sonar_simulation/install/log/autoproj main configuration-import.log for details
    last 7 lines are:

    Cloning into '/home/power/sonar_simulation/autoproj'...
    Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

autoproj bootstrap failed
To retry, first source the env.sh script with
source /home/power/sonar_simulation/env.sh
and then re-run autoproj bootstrap
autoproj bootstrap 'bootstrap'git'git@github.com:romulogcerqueira/sonar_simulation-buildconf.git'
Command failed
autoproj main configuration(/home/power/sonar_simulation/autoproj): failed in import phase
    'git clone -o autobuild git@github.com:romulogcerqueira/sonar_simulation-buildconf.git /home/power/sonar_simulation/autoproj' returned status 128
    see /home/power/sonar_simulation/install/log/autoproj main configuration-import.log for details
    last 7 lines are:

    Cloning into '/home/power/sonar_simulation/autoproj'...
    Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by fansystem** [comment]
Hi,

I am failed to build the package..
Could you explain this...?


Regards

**Comment by romulogcerqueira** [comment]
Hi @fansystem, this is what you need: https://help.github.com/articles/connecting-to-github-with-ssh/
