### ISSUE TITLE
Not able to view virtual underwater environment

### ISSUE THREAD

**Issue by shubhamwagh** [romulogcerqueira/sonar_simulation-buildconf#4]
Once I run the code 

ruby sonar_multibeam.rb

It shows three GUIs : 
1) Acoustic representation of the scenario
2) Sonar Pose control
3) Task Inspector

May I know how can I vie virtual underwater environment?
Thanks.

**Comment by romulogcerqueira** [comment]
This underwater imaging sonar simulation is part of a bigger project (FlatFish), and at this moment only the sonar simulator is provided. In the future we can share the 3D underwater environment, however I am putting my current efforts to extend the acoustic physics of simulator, including additive noise, attenuation and reverberation 😃.
