### ISSUE TITLE
How to grab consecutive sonar image frames in the simulator?

### ISSUE THREAD

**Issue by shubhamwagh** [romulogcerqueira/sonar_simulation-buildconf#5]
I am new to ruby and rock components framework. I want to capture consecutive sonar image frames in the simulator for the scene at that time instance. Any pointers as to how this can be done?
Code will be helpful.

Thanks.

**Comment by romulogcerqueira** [comment]
The current version of Rock framework outputs acoustic data as its datatype (base::samples::Sonar). There is no automatic export of acoustic image, however you can do it easily by plotting the acoustic data in polar coordinates. Please have a look to Rock Widget Collection (https://github.com/rock-core/gui-rock_widget_collection/blob/master/src/sonar_widget/SonarPlot.cc).
