### ISSUE TITLE
Directories don't install

### ISSUE THREAD

**Issue by matthewgiarra** [romulogcerqueira/sonar_simulation-buildconf#6]
After following your installation instructions, the codes appear to not have installed. The console messages appear to indicate that the installation worked, but clearly it hasn't.

``` 
$ pwd
/home/matt/sonar_simulation
$ tree
.
├── autoproj
│   ├── init.rb
│   ├── manifest
│   ├── overrides.d
│   └── README.md
├── autoproj_install
├── bootstrap.sh
├── env.sh
└── install
    ├── bin
    │   ├── gem
    │   ├── irb
    │   └── ruby
    ├── gems
    │   ├── Gemfile
    │   └── Gemfile.lock
    └── log
        ├── autoproj main configuration-import.log
        ├── autoproj-osdeps.log
        └── stats.log

6 directories, 14 files

$ find . -name "*sonar*" | wc -l
0
```
You may consider an installation procedure that doesn't rely on uncommon tools like `autoproj`. I'd like to check out your code but don't want to learn the ins and outs of `autoproj` to troubleshoot the installation.

**Comment by romulogcerqueira** [comment]
Hi @matthewgiarra , sorry for my long delay (I was sick). Could you give me more details about your problem? Recently I installed the simulator on Ubuntu 16.04 without problems. Could you repeat the installation?
