### ISSUE TITLE
typelib failed to build

### ISSUE THREAD

**Issue by chyphen777** [romulogcerqueira/sonar_simulation-buildconf#8]
I am interested in your sonar_simulation-buildconf software.  However, during sh bootstratp.sh, I got the following errors, related to typelib and boost.   Which version of boost to use?  Is it necessary to specify boost directories,  mine are under /usr/local/lib and /usr/local/include.  Thanks. CC

Trucated error message:

 building typelib (100%)
  ERROR: got an error processing typelib, waiting for pending jobs to end
  built rtt (18 warnings)
  updated environment
Command failed
typelib(/home/cchien/sonar_simulation/tools/typelib): failed in build phase
    'make --jobserver-fds=7,8 -j' returned status 2
    see /home/cchien/sonar_simulation/install/log/typelib-build.log for details
    last 10 lines are:

    test_typebuilder.cc:(.text.startup+0x2a9): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
    test_typebuilder.cc:(.text.startup+0x351): undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
    CMakeFiles/typelib_testsuite.dir/test_typebuilder.o:test_typebuilder.cc:(.text.startup+0x3f9): more undefined references to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)' follow
    collect2: error: ld returned 1 exit status
    test/CMakeFiles/typelib_testsuite.dir/build.make:386: recipe for target 'test/typelib_testsuite' failed
    make[2]: *** [test/typelib_testsuite] Error 1
    CMakeFiles/Makefile2:1121: recipe for target 'test/CMakeFiles/typelib_testsuite.dir/all' failed
    make[1]: *** [test/CMakeFiles/typelib_testsuite.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by chyphen777** [comment]
note:  I do have /usr/local/lib/libboost_unit_test_framework.so.1.58.0.  Do I need anything else?  CC

**Comment by chyphen777** [comment]
Boost 1.58 seems to be incompatible with the software.  Change it to Boost 1.66 and the issue resolved.  Thanks. CC

**Comment by 1ADZX** [comment]
hi,Thank you for the solution above, but I have a new problem now
typelib: using the castxml importer
  WARN: gui/osg_ocean from rock.gazebo does not have a manifest
  built typelib
  installed typelib
  set up Ruby package tools/pocolog
  configured CMake for rtt_typelib
  built rtt_typelib
  installed rtt_typelib
  setting up Ruby package orogen
  ERROR: got an error processing orogen, waiting for pending jobs to end
  configured CMake for tools/orogen_metadata
  configured CMake for perception/frame_helper
  environment already up-to-date
Command failed
orogen(/home/dzx/sonar_simulation/tools/orogen): failed in post-install phase
    '/home/dzx/.rbenv/versions/2.5.1/bin/ruby -S rake default' terminated by signal 6
    see /home/dzx/sonar_simulation/install/log/orogen-post-install.log for details
Do you have similar experience or know how to solve it？Thanks

**Comment by 1ADZX** [comment]
> Boost 1.58 seems to be incompatible with the software. Change it to Boost 1.66 and the issue resolved. Thanks. CC

hi,Thank you for the solution above, but I have a new problem now
typelib: using the castxml importer
WARN: gui/osg_ocean from rock.gazebo does not have a manifest
built typelib
installed typelib
set up Ruby package tools/pocolog
configured CMake for rtt_typelib
built rtt_typelib
installed rtt_typelib
setting up Ruby package orogen
ERROR: got an error processing orogen, waiting for pending jobs to end
configured CMake for tools/orogen_metadata
configured CMake for perception/frame_helper
environment already up-to-date
Command failed
orogen(/home/dzx/sonar_simulation/tools/orogen): failed in post-install phase
'/home/dzx/.rbenv/versions/2.5.1/bin/ruby -S rake default' terminated by signal 6
see /home/dzx/sonar_simulation/install/log/orogen-post-install.log for details
Do you have similar experience or know how to solve it？Thanks
