### ISSUE TITLE
syntax e

### ISSUE THREAD

**Issue by chyphen777** [romulogcerqueira/sonar_simulation-buildconf#9]
It got the same error 'bootstrap.sh: Syntax_error: "(" unexpected' as an old issue #7 which has been close. I redid installation from the scratch, and the error was gone, while I got other error. 

It seems the error occurs when "sh bootstrap.sh" is run more than once. So on a different, but somewhat related to" issue, how do I rebuild the package after making some change (e,g, errors in typelib with a different version of boost?), without using "sh bootstrap.sh (to avoid the error mentioned earlier).   Thanks. CC.

**Comment by chyphen777** [comment]
Sorry.  I am a new bite of ruby, etc.  Just figure out I could rebuild the software using aup and amke.  So this is is closed.  Thanks, CC

**Comment by 1ADZX** [comment]
> Sorry. I am a new bite of ruby, etc. Just figure out I could rebuild the software using aup and amke. So this is is closed. Thanks, CC

hello,I got the same error  'bootstrap.sh: Syntax_error: "(" unexpected' as an old issue, Can you tell me how to sovle it ?And i also met another error 'aup:The 'aup' command was not found. Do you want to enter:'
thanks
